import type {Metadata, Viewport} from 'next'
import './globals.css'
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import {CssBaseline} from "@mui/material";
import {ClerkProvider} from "@clerk/nextjs";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import ThemeRegistry from "@/app/ThemeRegistry";
import ConfirmDialog from "@/components/ConfirmDialog";

export const metadata: Metadata = {
  title: 'Math Quiz',
  description: 'Generated by create next app',
}

export const viewport: Viewport = {
    initialScale: 1,
    width: 'device-width',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <ClerkProvider>
    <html lang="en">
      <body>
      <CssBaseline enableColorScheme />
      <AppRouterCacheProvider>
        <ThemeRegistry options={{ key: 'mui' }}>
          <ConfirmDialog />
      {children}
      </ThemeRegistry>
      </AppRouterCacheProvider>
      </body>
    </html>
      </ClerkProvider>
  )
}
